######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 22 09:50:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
