######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 22 09:44:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
