######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 22 12:36:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
